### PR TITLE
Migrate and fix stream test

### LINKED ISSUE #360: Migrate and fix AkkaStreamAgentTest class
In https://github.com/ScalaConsultants/mesmer/pull/349 Akka Streaming Instrumentation code was copied to otel-extension and adapted for otel agent. However, the AkkaStreaminAgentTest suite was not migrated and it does not work now with the new implementation of AkkaStreamingAgent. The reason is that the ConnectionConstructorAdvice is not picked up by bytebuddy and that causes NPE when we call: 

```VirtualField.find(classOf[GraphInterpreter.Connection], classOf[ConnectionCounters]).get()```

Ideas for fixing (so far): 

1. (sounds best) use openTelemetry agent in tests so that it picks up the instrumentation code. We currently use only bare byteBuddy AgentBuilder that doesn't fully reflect the loading mechanism from otel agent
2. Try to eagerly load the ConnectionConstructorAdvice so that it gets picked up by the current testing code.

### PR DESCRIPTION
**Pull request by worekleszczy**
Closes #360 
___

## Summary:
Due to issues described in [here](https://github.com/raphw/byte-buddy/issues/757) and [here](https://stackoverflow.com/questions/51594148/duplicate-class-error-in-a-bytebuddy-agent-applying-advice) we were not getting `Connection` executed. We upcasted argument in the `@Advice` classes to `Object` to not trigger loading of the class before transformation is registered.

Note that `otelExtension` still depend on `agent` - this is left to satisfy compiler for other instrumentation modules, that are not yet migrated. This dependency must be removed in the future work.

### CODE REVIEW

File: otel-extension/src/main/java/io/scalac/mesmer/otelextension/MesmerAkkaStreamInstrumentationModule.java [hunk 1]
```diff
@@ -26,26 +26,27 @@ public MesmerAkkaStreamInstrumentationModule() {
...
+
+
+//        List<TypeInstrumentation> streamInstrumentations = new ArrayList<>();
+//
+//        streamInstrumentations.add(connectionConst);
+//
+//        streamInstrumentations.addAll(AkkaStreamAgent.agent().asOtelTypeInstrumentations());
+//
+//        return streamInstrumentations;
+        return AkkaStreamAgent.agent().asOtelTypeInstrumentations();
```
Comment (lgajowy) [inline otel-extension/src/main/java/io/scalac/mesmer/otelextension/MesmerAkkaStreamInstrumentationModule.java:49]: Note for the future: please never leave commented out code

```suggestion
        return AkkaStreamAgent.agent().asOtelTypeInstrumentations();
```

File: otel-extension/src/main/scala/io/scalac/mesmer/agent/Agent.scala [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+import net.bytebuddy.dynamic.DynamicType
+import net.bytebuddy.matcher.ElementMatcher
+import org.slf4j.LoggerFactory
+
+import scala.jdk.CollectionConverters.SeqHasAsJava
+
+import io.scalac.mesmer.agent.util.i13n
+import io.scalac.mesmer.agent.util.i13n.InstrumentationDetails
+
+final case class Agent private (private[agent] val instrumentations: Set[AgentInstrumentation]) extends {
```
Comment (lgajowy) [inline otel-extension/src/main/scala/io/scalac/mesmer/agent/Agent.scala:18]: Just a note for the future: as you noted in some previous reviews, it's hard to review copied code. So we should mitigate this situation in the future by not doing both moving and changing code in the same PRs. This way we see what PR exactly fixes the problem and what PRs are just pure refactoring.

File: otel-extension/src/test/scala/io/scalac/mesmer/agent/utils/InstallAgent.scala [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+abstract class InstallAgent extends TestSuite with BeforeAndAfterAll {
+
+  protected def agent: Agent = allInstrumentations
+
+  private val builder = new AgentBuilder.Default(
+    new ByteBuddy()
+      .`with`(TypeValidation.DISABLED)
+  )
+    .`with`(AgentBuilder.RedefinitionStrategy.REDEFINITION)
+    .`with`(TypeStrategy.Default.REDEFINE)
```
Comment (lgajowy) [inline otel-extension/src/test/scala/io/scalac/mesmer/agent/utils/InstallAgent.scala:31]: That's changed needleslly. I will revert it back to RETRANSFORMATION. The tests will still pass

**Review by lgajowy — CHANGES_REQUESTED** [review]

File: build.sbt [hunk 4]
```diff
@@ -116,13 +116,24 @@ lazy val otelExtension = (project in file("otel-extension"))
...
+    Test / parallelExecution := true,
+    Test / testGrouping := ((Test / testGrouping).value flatMap { group =>
+      group.tests.map { test =>
+        Tests.Group(name = test.name, tests = Seq(test), runPolicy = group.runPolicy)
+      }
+    }),
+    Test / testOnly / testGrouping := (Test / testGrouping).value
   )
-  .dependsOn(core, agent)
+  .dependsOn(core % "provided->compile;test->test", agent)
```
Comment (lgajowy) [inline build.sbt:136]:
```suggestion
  .dependsOn(core, agent)
```

Otherwise the app fails during startup with: 

```
[error] ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
[error] java.lang.NoClassDefFoundError: io/scalac/mesmer/core/module/MesmerModule
[error]         at io.scalac.mesmer.agent.config.MesmerConfigPropertySourceProvider$.modules(MesmerConfigPropertySource.scala:11)
[error]         at io.scalac.mesmer.agent.config.MesmerConfigPropertySourceProvider$.getProperties(MesmerConfigPropertySource.scala:24)
[error]         at io.scalac.mesmer.agent.config.MesmerConfigPropertySourceProvider.getProperties(MesmerConfigPropertySource.scala)
[error]         at io.scalac.mesmer.agent.config.MesmerConfigPropertySource.getProperties(MesmerConfigPropertySource.java:13)
[error]         at io.opentelemetry.javaagent.tooling.config.ConfigInitializer.loadSpiConfiguration(ConfigInitializer.java:47)
[error]         at io.opentelemetry.javaagent.tooling.config.ConfigInitializer.initialize(ConfigInitializer.java:30)
[error]         at io.opentelemetry.javaagent.tooling.AgentInstaller.<clinit>(AgentInstaller.java:81)
[error]         at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:65)
[error]         at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:37)
[error]         at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:55)
[error]         at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:44)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
[error]         at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
[error] Caused by: java.lang.ClassNotFoundException: io.scalac.mesmer.core.module.MesmerModule
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[error]         ... 17 more
```

**Review by lgajowy — CHANGES_REQUESTED** [review]

File: otel-extension/src/main/java/io/scalac/mesmer/otelextension/MesmerAkkaStreamInstrumentationModule.java (hunk 1 above)
Comment (lgajowy) [reply otel-extension/src/main/java/io/scalac/mesmer/otelextension/MesmerAkkaStreamInstrumentationModule.java:49]: I'm not sure if we even need provided->compile in agent sbt config as well. [It means](https://www.scala-sbt.org/1.x/docs/Multi-Project.html#Per-configuration+classpath+dependencies) that "provided configuration in agent depends on compile configuration in core". Why would such sophisticated configuration be needed in agent that is meant only to be a fat jar added as a javaagent (not as a provided-scope dependency)? 

Anyways when we merge everything in otel-extension It will work in both variants.

File: build.sbt (hunk 4 above)
Comment (lgajowy) [reply build.sbt:136]: I'm not sure if we even need provided->compile in agent sbt config as well. [It means](https://www.scala-sbt.org/1.x/docs/Multi-Project.html#Per-configuration+classpath+dependencies) that "provided configuration in agent depends on compile configuration in core". Why would such sophisticated configuration be needed in agent that is meant only to be a fat jar added as a javaagent (not as a provided-scope dependency)? 

Anyways when we merge everything in otel-extension It will work in both variants.

**Review by lgajowy — APPROVED** [review]

**Comment by lgajowy** [comment]
@worekleszczy please look at the commits with fixes from me (it was easier to just code that) and if no objections feel free to merge
